import './globals.css';
import type { Metadata } from 'next';
import Recoil from './components/Recoil';
import Image from 'next/image';
import backgroundImg from '@/assets/Cloudy.svg';

export const metadata: Metadata = {
    title: 'workout log for overload',
    description: 'Generated by ehhdrud',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html>
            <body>
                <Image
                    src={backgroundImg}
                    alt="img"
                    fill
                    objectFit="cover"
                    style={{ zIndex: -1 }}
                />
                <h1 className="main-title">
                    <p className="title-top">WORKOUT LOG</p>

                    <div className="title-bottom">
                        💪OVERLOAD<p className="right-emoji">💪</p>
                    </div>
                </h1>

                <Recoil>{children}</Recoil>
            </body>
        </html>
    );
}
