import './globals.css';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'workout log for overload',
    description: 'Generated by ehhdrud',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html>
            <body>
                <h1>
                    <p>workout log</p>
                    <div>
                        💪OVERLOAD<p>💪</p>
                    </div>
                </h1>
                {children}
            </body>
        </html>
    );
}
